[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
build_flags =
    -I src
    -I lib
    -I src/shared
    -fpermissive

[env:Panel]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
board = ESP-LCD
build_flags = 
    -I src/panel
    -I src/panel/config
    -I lib
    -fpermissive
    -DBOARD_HAS_PSRAM
    -DLV_CONF_INCLUDE_SIMPLE
    -D LV_CONF_PATH="${PROJECT_DIR}/lib/lv_conf.h"
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
    -DLV_LVGL_H_INCLUDE_SIMPLE
    ${env.build_flags}
build_src_filter =
    +<panel/>
    +<shared/>
    -<peripheral/>
lib_deps =
    lvgl/lvgl@8.4.0

[env:Peripheral-Fans]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
board = esp32-c3-devkitm-1
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    ${env.build_flags}
build_src_filter =
    +<peripheral/fans>
    +<shared/>
    -<panel/>

[env:Peripheral-Key]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
board = esp32-c6-devkitm-1
board_build.partitions = huge_app.csv
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    ${env.build_flags}
build_src_filter =
    +<peripheral/key>
    +<shared/>
    -<panel/>

[env:Peripheral-Lights]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
board = esp32-c3-devkitm-1
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    ${env.build_flags}
build_src_filter =
    +<peripheral/lights>
    +<shared/>
    -<panel/>
