[env:ESP-LCD]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = ESP-LCD
framework = arduino
monitor_speed = 115200
build_flags = 
    -DBOARD_HAS_PSRAM
    -DLV_CONF_INCLUDE_SIMPLE
    -D LV_CONF_PATH="${PROJECT_DIR}/lib/lv_conf.h"
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -I src
    -I lib
    -fpermissive
lib_deps =
    lvgl/lvgl@8.4.0