[env]
framework = arduino
monitor_speed = 115200
build_flags =
    -I src
    -I lib
    -I src/shared
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_CDC_ON_BOOT=1

[peripheral]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-esp32-c6
board_build.partitions = huge_app.csv
build_flags =
    -DARDUINO_USB_MODE=1

[env:Panel]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = ESP-LCD
upload_port = /dev/cu.usbmodem111301
monitor_port = /dev/cu.usbmodem111301
build_flags = 
    ${env.build_flags}
    -I src/panel
    -I src/panel/config
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_CONF_PATH="${PROJECT_DIR}/lib/lv_conf.h"
    -DLV_LVGL_H_INCLUDE_SIMPLE
build_src_filter =
    +<panel/>
    +<shared/>
    -<peripheral/>
lib_deps =
    lvgl/lvgl@8.4.0

[env:Peripheral-Fans]
platform = ${peripheral.platform}
board = ${peripheral.board}
board_build.partitions = ${peripheral.board_build.partitions}
build_flags =
    ${env.build_flags}
    ${peripheral.build_flags}
build_src_filter =
    +<peripheral/fans>
    +<shared/>
    -<panel/>

[env:Peripheral-Key]
platform = ${peripheral.platform}
board = ${peripheral.board}
build_flags =
    ${env.build_flags}
    ${peripheral.build_flags}
build_src_filter =
    +<peripheral/key>
    +<shared/>
    -<panel/>

[env:Peripheral-Lights]
platform = ${peripheral.platform}
board = ${peripheral.board}
build_flags =
    ${env.build_flags}
    ${peripheral.build_flags}
build_src_filter =
    +<peripheral/lights>
    +<shared/>
    -<panel/>
