from pathlib import Path

Import("env")

PROJECT_DIR = Path(env.subst("$PROJECT_DIR"))
ENV_FILE = PROJECT_DIR / ".env"
OUT_DIR = PROJECT_DIR / ".pio" / "generated"
OUT_FILE = OUT_DIR / "MeshSecrets.generated.h"

ROLES = {
    "unknown": "Unknown",
    "panel": "Panel",
    "fans": "Fans",
    "key": "Key",
    "lights": "Lights",
}


def parse_env(path):
    values = {}
    for line_no, raw_line in enumerate(path.read_text().splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise ValueError(f"{path}:{line_no}: expected KEY=VALUE")
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def bytes_from_ascii(name, value):
    encoded = value.encode("ascii")
    if len(encoded) != 16:
        raise ValueError(f"{name} must be exactly 16 ASCII characters")
    return ", ".join(f"0x{byte:02X}" for byte in encoded)


def parse_mac(value):
    parts = value.replace("-", ":").split(":")
    if len(parts) != 6:
        raise ValueError(f"invalid MAC address: {value}")
    try:
        return [int(part, 16) for part in parts]
    except ValueError as exc:
        raise ValueError(f"invalid MAC address: {value}") from exc


def parse_node(value):
    parts = [part.strip() for part in value.split(",", 3)]
    if len(parts) != 4:
        raise ValueError(f"node entries must be role,logical_id,mac,label: {value}")

    role, logical_id, mac, label = parts
    role_name = ROLES.get(role.lower())
    if role_name is None:
        raise ValueError(f"unknown node role: {role}")
    mac_bytes = parse_mac(mac)
    return role_name, int(logical_id, 0), mac_bytes, label.replace("\\", "\\\\").replace('"', '\\"')


def main():
    if not ENV_FILE.exists():
        raise RuntimeError("Missing .env. Copy .env.example to .env and fill in mesh secrets.")

    values = parse_env(ENV_FILE)
    channel = int(values.get("MESH_CHANNEL", "1"), 0)
    pmk = bytes_from_ascii("MESH_PMK", values["MESH_PMK"])
    lmk = bytes_from_ascii("MESH_LMK", values["MESH_LMK"])

    node_keys = sorted(
        (key for key in values if key.startswith("MESH_NODE_")),
        key=lambda key: int(key.removeprefix("MESH_NODE_")),
    )
    if not node_keys:
        raise ValueError("At least one MESH_NODE_<N> entry is required")

    node_lines = []
    for key in node_keys:
        role_name, logical_id, mac_bytes, label = parse_node(values[key])
        mac = ", ".join(f"0x{byte:02X}" for byte in mac_bytes)
        node_lines.append(
            f'        {{NodeRole::{role_name}, {logical_id}, {{{mac}}}, "{label}"}},'
        )

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(
        "\n".join(
            [
                "#pragma once",
                "",
                "// Generated by tools/generate_mesh_config.py from .env.",
                "// Do not edit or commit this file.",
                "namespace mesh {",
                f"    constexpr uint8_t kMeshChannel = {channel};",
                f"    constexpr uint8_t kMeshPmk[16] = {{{pmk}}};",
                f"    constexpr uint8_t kMeshLmk[16] = {{{lmk}}};",
                "",
                "    constexpr RegistrySeedEntry kRegistrySeed[] = {",
                *node_lines,
                "    };",
                "",
                "    constexpr size_t kRegistrySeedCount = sizeof(kRegistrySeed) / sizeof(kRegistrySeed[0]);",
                "} // namespace mesh",
                "",
            ]
        )
    )
    env.Append(CPPPATH=[str(OUT_DIR)])


main()
